name: Laravel CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [10.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
      with:
        path: /home/ubuntu/jurnalib
    - name: Build frontend
      run: sail npm run build
