name: Laravel CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: install Laravel package
      run: docker run --rm --pull=always -v "$(pwd)":/opt -w /opt laravelsail/php82-composer:latest composer install --ignore-platform-reqs
    - name: Install Node Packages
      run: ./vendor/bin/sail npm install
    - name: Build frontend
      working-directory: /home/ubuntu/jurnalib
      run: ./vendor/bin/sail npm run build
